update channel set xmltvid="6941.dvb.guide" where callsign="BBC One HD";
update channel set channum="101" where callsign="BBC One HD";
update channel set xmltvid="6940.dvb.guide" where callsign="BBC Two HD";
update channel set channum="102" where callsign="BBC Two HD";
update channel set xmltvid="21010.dvb.guide" where callsign="ITV HD";
update channel set channum="103" where callsign="ITV HD";
update channel set xmltvid="21200.dvb.guide" where callsign="Channel 4 HD";
update channel set channum="104" where callsign="Channel 4 HD";
update channel set xmltvid="7701.dvb.guide" where callsign="Channel 5";
update channel set channum="105" where callsign="Channel 5";
update channel set xmltvid="5718.dvb.guide" where callsign="Sky1";
update channel set channum="106" where callsign="Sky1";
update channel set xmltvid="5715.dvb.guide" where callsign="Sky Living";
update channel set channum="107" where callsign="Sky Living";
update channel set xmltvid="5711.dvb.guide" where callsign="Sky Atlantic ";
update channel set channum="108" where callsign="Sky Atlantic ";
update channel set xmltvid="7657.dvb.guide" where callsign="Watch";
update channel set channum="109" where callsign="Watch";
update channel set xmltvid="6504.dvb.guide" where callsign="GOLD";
update channel set channum="110" where callsign="GOLD";
update channel set xmltvid="7620.dvb.guide" where callsign="Dave";
update channel set channum="111" where callsign="Dave";
update channel set xmltvid="51084.dvb.guide" where callsign="ComedyCentral";
update channel set channum="112" where callsign="ComedyCentral";
update channel set xmltvid="52220.dvb.guide" where callsign="Universal+1";
update channel set channum="113" where callsign="Universal+1";
update channel set xmltvid="52250.dvb.guide" where callsign="Syfy";
update channel set channum="114" where callsign="Syfy";
update channel set xmltvid="10070.dvb.guide" where callsign="ITV2";
update channel set channum="118" where callsign="ITV2";
update channel set xmltvid="10260.dvb.guide" where callsign="ITV3";
update channel set channum="119" where callsign="ITV3";
update channel set xmltvid="10072.dvb.guide" where callsign="ITV4";
update channel set channum="120" where callsign="ITV4";
update channel set xmltvid="5709.dvb.guide" where callsign="Sky2";
update channel set channum="121" where callsign="Sky2";
update channel set xmltvid="5712.dvb.guide" where callsign="Sky Living+1";
update channel set channum="122" where callsign="Sky Living+1";
update channel set xmltvid="10135.dvb.guide" where callsign="ITV Encore";
update channel set channum="123" where callsign="ITV Encore";
update channel set xmltvid="5515.dvb.guide" where callsign="FOX";
update channel set channum="124" where callsign="FOX";
update channel set xmltvid="7001.dvb.guide" where callsign="MTV";
update channel set channum="126" where callsign="MTV";
update channel set xmltvid="51083.dvb.guide" where callsign="ComedyCent+1";
update channel set channum="127" where callsign="ComedyCent+1";
update channel set xmltvid="51086.dvb.guide" where callsign="ComedyXtra";
update channel set channum="128" where callsign="ComedyXtra";
update channel set xmltvid="10021.dvb.guide" where callsign="ITV +1";
update channel set channum="131" where callsign="ITV +1";
update channel set xmltvid="6521.dvb.guide" where callsign="alibi";
update channel set channum="132" where callsign="alibi";
update channel set xmltvid="7605.dvb.guide" where callsign="GOLD +1";
update channel set channum="133" where callsign="GOLD +1";
update channel set xmltvid="8312.dvb.guide" where callsign="Channel 4 +1";
update channel set channum="135" where callsign="Channel 4 +1";
update channel set xmltvid="9208.dvb.guide" where callsign="E4";
update channel set channum="136" where callsign="E4";
update channel set xmltvid="8300.dvb.guide" where callsign="E4+1";
update channel set channum="137" where callsign="E4+1";
update channel set xmltvid="8340.dvb.guide" where callsign="More4";
update channel set channum="138" where callsign="More4";
update channel set xmltvid="9230.dvb.guide" where callsign="More4 +1";
update channel set channum="139" where callsign="More4 +1";
update channel set xmltvid="21250.dvb.guide" where callsign="4seven";
update channel set channum="140" where callsign="4seven";
update channel set xmltvid="52415.dvb.guide" where callsign="DMAX";
update channel set channum="144" where callsign="DMAX";
update channel set xmltvid="6031.dvb.guide" where callsign="Challenge";
update channel set channum="145" where callsign="Challenge";
update channel set xmltvid="52505.dvb.guide" where callsign="CBS Reality";
update channel set channum="146" where callsign="CBS Reality";
update channel set xmltvid="52102.dvb.guide" where callsign="CBS Reality+1";
update channel set channum="147" where callsign="CBS Reality+1";
update channel set xmltvid="53710.dvb.guide" where callsign="CBS Action";
update channel set channum="148" where callsign="CBS Action";
update channel set xmltvid="50903.dvb.guide" where callsign="CBS Drama";
update channel set channum="149" where callsign="CBS Drama";
update channel set xmltvid="53215.dvb.guide" where callsign="E!";
update channel set channum="151" where callsign="E!";
update channel set xmltvid="5107.dvb.guide" where callsign="Pick";
update channel set channum="152" where callsign="Pick";
update channel set xmltvid="5107.dvb.guide" where callsign="Pick+1";
update channel set channum="153" where callsign="Pick+1";
update channel set xmltvid="52446.dvb.guide" where callsign="TLC+1";
update channel set channum="154" where callsign="TLC+1";
update channel set xmltvid="7615.dvb.guide" where callsign="Watch +1";
update channel set channum="155" where callsign="Watch +1";
update channel set xmltvid="5716.dvb.guide" where callsign="Lifetime";
update channel set channum="156" where callsign="Lifetime";
update channel set xmltvid="7150.dvb.guide" where callsign="Sony TV";
update channel set channum="157" where callsign="Sony TV";
update channel set xmltvid="7624.dvb.guide" where callsign="Dave ja vu";
update channel set channum="158" where callsign="Dave ja vu";
update channel set xmltvid="51087.dvb.guide" where callsign="ComedyXtra+1";
update channel set channum="159" where callsign="ComedyXtra+1";
update channel set xmltvid="7005.dvb.guide" where callsign="MTV+1";
update channel set channum="160" where callsign="MTV+1";
update channel set xmltvid="6026.dvb.guide" where callsign="Challenge+1";
update channel set channum="164" where callsign="Challenge+1";
update channel set xmltvid="5402.dvb.guide" where callsign="FOX+";
update channel set channum="165" where callsign="FOX+";
update channel set xmltvid="6522.dvb.guide" where callsign="Drama";
update channel set channum="166" where callsign="Drama";
update channel set xmltvid="6211.dvb.guide" where callsign="QUEST";
update channel set channum="167" where callsign="QUEST";
update channel set xmltvid="1403.dvb.guide" where callsign="Sky1 +1";
update channel set channum="172" where callsign="Sky1 +1";
update channel set xmltvid="1413.dvb.guide" where callsign="Sky Atlantic+1";
update channel set channum="173" where callsign="Sky Atlantic+1";
update channel set xmltvid="7710.dvb.guide" where callsign="5 USA";
update channel set channum="174" where callsign="5 USA";
update channel set xmltvid="7716.dvb.guide" where callsign="Channel 5+24";
update channel set channum="175" where callsign="Channel 5+24";
update channel set xmltvid="7715.dvb.guide" where callsign="5*";
update channel set channum="176" where callsign="5*";
update channel set xmltvid="7720.dvb.guide" where callsign="Channel 5+1";
update channel set channum="177" where callsign="Channel 5+1";
update channel set xmltvid="10075.dvb.guide" where callsign="ITVBe";
update channel set channum="179" where callsign="ITVBe";
update channel set xmltvid="10165.dvb.guide" where callsign="ITV2+1";
update channel set channum="180" where callsign="ITV2+1";
update channel set xmltvid="53271.dvb.guide" where callsign="Sony TV +1";
update channel set channum="181" where callsign="Sony TV +1";
update channel set xmltvid="53380.dvb.guide" where callsign="True Drama";
update channel set channum="183" where callsign="True Drama";
update channel set xmltvid="53375.dvb.guide" where callsign="True Ent";
update channel set channum="184" where callsign="True Ent";
update channel set xmltvid="54110.dvb.guide" where callsign="more>movies";
update channel set channum="185" where callsign="more>movies";
update channel set xmltvid="51120.dvb.guide" where callsign="m>movies+1";
update channel set channum="186" where callsign="m>movies+1";
update channel set xmltvid="52005.dvb.guide" where callsign="Showcase +1";
update channel set channum="192" where callsign="Showcase +1";
update channel set xmltvid="10261.dvb.guide" where callsign="ITV3+1";
update channel set channum="193" where callsign="ITV3+1";
update channel set xmltvid="52280.dvb.guide" where callsign="Syfy +1";
update channel set channum="194" where callsign="Syfy +1";
update channel set xmltvid="52430.dvb.guide" where callsign="QUEST+1";
update channel set channum="195" where callsign="QUEST+1";
update channel set xmltvid="7630.dvb.guide" where callsign="alibi +1";
update channel set channum="196" where callsign="alibi +1";
update channel set xmltvid="53525.dvb.guide" where callsign="Lifetime+1";
update channel set channum="197" where callsign="Lifetime+1";
update channel set xmltvid="52455.dvb.guide" where callsign="TLC+2";
update channel set channum="200" where callsign="TLC+2";
update channel set xmltvid="10015.dvb.guide" where callsign="ITV4+1";
update channel set channum="206" where callsign="ITV4+1";
update channel set xmltvid="6951.dvb.guide" where callsign="BBC Three HD";
update channel set channum="210" where callsign="BBC Three HD";
update channel set xmltvid="8931.dvb.guide" where callsign="BBC Four HD";
update channel set channum="211" where callsign="BBC Four HD";
update channel set xmltvid="5719.dvb.guide" where callsign="Sky Arts 1";
update channel set channum="221" where callsign="Sky Arts 1";
update channel set xmltvid="6030.dvb.guide" where callsign="Sky Livingit";
update channel set channum="222" where callsign="Sky Livingit";
update channel set xmltvid="6025.dvb.guide" where callsign="Sky Livingit+1";
update channel set channum="223" where callsign="Sky Livingit+1";
update channel set xmltvid="53276.dvb.guide" where callsign="E! +1";
update channel set channum="229" where callsign="E! +1";
update channel set xmltvid="52420.dvb.guide" where callsign="DMAX+1";
update channel set channum="233" where callsign="DMAX+1";
update channel set xmltvid="52016.dvb.guide" where callsign="FilmOn.TV";
update channel set channum="237" where callsign="FilmOn.TV";
update channel set xmltvid="6208.dvb.guide" where callsign="Home & Health";
update channel set channum="240" where callsign="Home & Health";
update channel set xmltvid="52450.dvb.guide" where callsign="Home&Health+";
update channel set channum="241" where callsign="Home&Health+";
update channel set xmltvid="52440.dvb.guide" where callsign="Discovery Shed";
update channel set channum="242" where callsign="Discovery Shed";
update channel set xmltvid="6501.dvb.guide" where callsign="Home";
update channel set channum="243" where callsign="Home";
update channel set xmltvid="6508.dvb.guide" where callsign="Good Food";
update channel set channum="244" where callsign="Good Food";
update channel set xmltvid="6508.dvb.guide" where callsign="Really";
update channel set channum="245" where callsign="Really";
update channel set xmltvid="7600.dvb.guide" where callsign="Home+1";
update channel set channum="246" where callsign="Home+1";
update channel set xmltvid="7626.dvb.guide" where callsign="Good Food +1";
update channel set channum="247" where callsign="Good Food +1";
update channel set xmltvid="52500.dvb.guide" where callsign="Food Network";
update channel set channum="248" where callsign="Food Network";
update channel set xmltvid="54102.dvb.guide" where callsign="Travel Channel";
update channel set channum="249" where callsign="Travel Channel";
update channel set xmltvid="52510.dvb.guide" where callsign="Food Netwrk+1";
update channel set channum="250" where callsign="Food Netwrk+1";
update channel set xmltvid="55236.dvb.guide" where callsign="holiday+cruise";
update channel set channum="256" where callsign="holiday+cruise";
update channel set xmltvid="4900.dvb.guide" where callsign="Sky Arts 2";
update channel set channum="262" where callsign="Sky Arts 2";