update channel set channum="602" where callsign="CN+1";
update channel set xmltvid="50215.dvb.guide" where callsign="CN+1";
update channel set channum="604" where callsign="Nickelodeon";
update channel set xmltvid="51091.dvb.guide" where callsign="Nickelodeon";
update channel set channum="605" where callsign="Nickelodeon+1";
update channel set xmltvid="5561.dvb.guide" where callsign="Nickelodeon+1";
update channel set channum="606" where callsign="Nicktoons";
update channel set xmltvid="5562.dvb.guide" where callsign="Nicktoons";
update channel set channum="607" where callsign="Disney XD";
update channel set xmltvid="9101.dvb.guide" where callsign="Disney XD";
update channel set channum="608" where callsign="Disney XD+1";
update channel set xmltvid="9104.dvb.guide" where callsign="Disney XD+1";
update channel set channum="609" where callsign="Disney Chnl";
update channel set xmltvid="9102.dvb.guide" where callsign="Disney Chnl";
update channel set channum="610" where callsign="Disney Chnl+1";
update channel set xmltvid="9105.dvb.guide" where callsign="Disney Chnl+1";
update channel set channum="611" where callsign="Disney Junior";
update channel set xmltvid="9103.dvb.guide" where callsign="Disney Junior";
update channel set channum="612" where callsign="Disney Junior+";
update channel set xmltvid="9106.dvb.guide" where callsign="Disney Junior+";
update channel set channum="613" where callsign="CBBC HD";
update channel set xmltvid="6952.dvb.guide" where callsign="CBBC HD";
update channel set channum="614" where callsign="CBeebies HD";
update channel set xmltvid="8932.dvb.guide" where callsign="CBeebies HD";
update channel set channum="615" where callsign="Nick Jr.";
update channel set xmltvid="5563.dvb.guide" where callsign="Nick Jr";
update channel set channum="616" where callsign="POP";
update channel set xmltvid="53340.dvb.guide" where callsign="POP";
update channel set channum="617" where callsign="Tiny Pop";
update channel set xmltvid="53330.dvb.guide" where callsign="Tiny Pop";
update channel set channum="619" where callsign="Cartoonito";
update channel set xmltvid="5521.dvb.guide" where callsign="Cartoonito";
update channel set channum="621" where callsign="CITV";
update channel set xmltvid="10071.dvb.guide" where callsign="CITV";
update channel set channum="623" where callsign="BabyTV";
update channel set xmltvid="5564.dvb.guide" where callsign="BabyTV";
update channel set channum="625" where callsign="Tiny Pop +1";
update channel set xmltvid="53345.dvb.guide" where callsign="Tiny Pop +1";
update channel set channum="626" where callsign="PopGirl";
update channel set xmltvid="53360.dvb.guide" where callsign="PopGirl";
update channel set channum="627" where callsign="Kix";
update channel set xmltvid="53350.dvb.guide" where callsign="Kix";
update channel set channum="629" where callsign="POP+1";
update channel set xmltvid="53370.dvb.guide" where callsign="POP+1";
update channel set channum="630" where callsign="Nick Jr+1";
update channel set xmltvid="51090.dvb.guide" where callsign="Nick Jr+1";
