update channel set channum="520" where callsign="Discovery";
update channel set xmltvid="6210.dvb.guide" where callsign="Discovery";
update channel set channum="521" where callsign="Discovery+1";
update channel set xmltvid="6204.dvb.guide" where callsign="Discovery+1";
update channel set channum="522" where callsign="ID";
update channel set xmltvid="52400.dvb.guide" where callsign="ID";
update channel set channum="523" where callsign="Animal Planet";
update channel set xmltvid="6202.dvb.guide" where callsign="Animal Planet";
update channel set channum="524" where callsign="Disc.Turbo";
update channel set xmltvid="6209.dvb.guide" where callsign="Disc.Turbo";
update channel set channum="525" where callsign="Disc.Science";
update channel set xmltvid="6206.dvb.guide" where callsign="Disc.Science";
update channel set channum="527" where callsign="Nat Geo+1hr";
update channel set xmltvid="4806.dvb.guide" where callsign="Nat Geo+1hr";
update channel set channum="530" where callsign="History";
update channel set xmltvid="4653.dvb.guide" where callsign="History";
update channel set channum="531" where callsign="History +1 hour";
update channel set xmltvid="5003.dvb.guide" where callsign="History +1 hour";
update channel set channum="535" where callsign="Disc.History";
update channel set xmltvid="6207.dvb.guide" where callsign="Disc.History";
update channel set channum="536" where callsign="Disc.History+1";
update channel set xmltvid="52435.dvb.guide" where callsign="Disc.History+1";
update channel set channum="549" where callsign="Animal Plnt+1";
update channel set xmltvid="52405.dvb.guide" where callsign="Animal Plnt+1";
update channel set channum="555" where callsign="ID+1";
update channel set xmltvid="52426.dvb.guide" where callsign="ID+1";
update channel set channum="557" where callsign="Disc.Sci+1";
update channel set xmltvid="52410.dvb.guide" where callsign="Disc.Sci+1";