update channel set channum="301" where callsign="Sky Premiere";
update channel set xmltvid="4404.dvb.guide" where callsign="Sky Premiere";
update channel set channum="302" where callsign="Sky Prem+1";
update channel set xmltvid="4405.dvb.guide" where callsign="Sky Prem+1";
update channel set channum="303" where callsign="Sky Showcase";
update channel set xmltvid="5720.dvb.guide" where callsign="Sky Showcase";
update channel set channum="304" where callsign="Sky Greats";
update channel set xmltvid="5650.dvb.guide" where callsign="Sky Greats";
update channel set channum="305" where callsign="Sky Disney";
update channel set xmltvid="4308.dvb.guide" where callsign="Sky Disney";
update channel set xmltvid="4403.dvb.guide" where callsign="Sky Family";
update channel set channum="306" where callsign="Sky Family";
update channel set xmltvid="4302.dvb.guide" where callsign="Sky Action";
update channel set channum="307" where callsign="Sky Action";
update channel set xmltvid="4303.dvb.guide" where callsign="Sky Comedy";
update channel set channum="308" where callsign="Sky Comedy";
update channel set xmltvid="4406.dvb.guide" where callsign="Sky Thriller";
update channel set channum="309" where callsign="Sky Thriller";
update channel set channum="310" where callsign="Sky DramaRom";
update channel set xmltvid="5502.dvb.guide" where callsign="Sky DramaRom";
update channel set channum="311" where callsign="Sky ScFi/Horror";
update channel set xmltvid="4304.dvb.guide" where callsign="Sky ScFi/Horror";
update channel set channum="312" where callsign="Sky Select";
update channel set xmltvid="4306.dvb.guide" where callsign="Sky Select";
update channel set channum="315" where callsign="Film4";
update channel set xmltvid="9220.dvb.guide" where callsign="Film4";
update channel set channum="316" where callsign="Film4 +1";
update channel set xmltvid="9225.dvb.guide" where callsign="Film4 +1";
update channel set xmltvid="5714.dvb.guide" where callsign="TCM";
update channel set channum="317" where callsign="TCM";
update channel set xmltvid="52175.dvb.guide" where callsign="TCM+1";
update channel set channum="318" where callsign="TCM+1";
update channel set xmltvid="52105.dvb.guide" where callsign="horror channel";
update channel set channum="319" where callsign="horror channel";
update channel set xmltvid="53700.dvb.guide" where callsign="horror ch+1";
update channel set channum="320" where callsign="horror ch+1";
update channel set channum="321" where callsign="True Movies 1";
update channel set xmltvid="53320.dvb.guide" where callsign="True Movies 1";
update channel set xmltvid="53325.dvb.guide" where callsign="True Movies2";
update channel set channum="322" where callsign="True Movies2";
update channel set channum="323" where callsign="Sony Movies";
update channel set xmltvid="51117.dvb.guide" where callsign="Sony Movies";
update channel set channum="324" where callsign="Sony Movies+1";
update channel set xmltvid="51119.dvb.guide" where callsign="Sony Movies+1";
update channel set channum="325" where callsign="movies4men";
update channel set xmltvid="51116.dvb.guide" where callsign="movies4men";
update channel set channum="326" where callsign="mov4men+1";
update channel set xmltvid="51118.dvb.guide" where callsign="mov4men+1";
update channel set xmltvid="52265.dvb.guide" where callsign="Movies 24";
update channel set channum="327" where callsign="Movies 24";
update channel set xmltvid="52270.dvb.guide" where callsign="Movies 24+";
update channel set channum="328" where callsign="Movies 24+";
