update channel set channum="350" where callsign="MTV MUSIC";
update channel set xmltvid="7012.dvb.guide" where callsign="MTV MUSIC";
update channel set channum="351" where callsign="MTV BASE";
update channel set xmltvid="7007.dvb.guide" where callsign="MTV BASE";
update channel set channum="352" where callsign="MTV HITS";
update channel set xmltvid="7006.dvb.guide" where callsign="MTV HITS";
update channel set channum="353" where callsign="MTV DANCE";
update channel set xmltvid="7014.dvb.guide" where callsign="MTV DANCE";
update channel set channum="354" where callsign="MTV ROCKS";
update channel set xmltvid="7003.dvb.guide" where callsign="MTV ROCKS";
update channel set channum="355" where callsign="MTV CLASSIC";
update channel set xmltvid="7008.dvb.guide" where callsign="MTV CLASSIC";
update channel set channum="356" where callsign="VH1";
update channel set xmltvid="7002.dvb.guide" where callsign="VH1";
update channel set channum="357" where callsign="VIVA";
update channel set xmltvid="7009.dvb.guide" where callsign="VIVA";
update channel set channum="358" where callsign="MTV LIVE";
update channel set xmltvid="53150.dvb.guide" where callsign="MTV LIVE";
update channel set channum="359" where callsign="The Box";
update channel set xmltvid="12005.dvb.guide" where callsign="The Box";
update channel set channum="360" where callsign="4Music";
update channel set xmltvid="12000.dvb.guide" where callsign="4Music";
update channel set channum="361" where callsign="KISS";
update channel set xmltvid="12010.dvb.guide" where callsign="KISS";
update channel set channum="362" where callsign="Smash Hits!";
update channel set xmltvid="12020.dvb.guide" where callsign="Smash Hits!";
update channel set channum="363" where callsign="Magic";
update channel set xmltvid="50860.dvb.guide" where callsign="Magic";
update channel set channum="365" where callsign="Chart Show TV";
update channel set xmltvid="53365.dvb.guide" where callsign="Chart Show TV";
update channel set channum="367" where callsign="The Vault";
update channel set xmltvid="53355.dvb.guide" where callsign="The Vault";
update channel set channum="368" where callsign="Kerrang!";
update channel set xmltvid="12015.dvb.guide" where callsign="Kerrang!";
update channel set channum="369" where callsign="Vintage TV";
update channel set xmltvid="52180.dvb.guide" where callsign="Vintage TV";
update channel set channum="370" where callsign="Planet Pop";
update channel set xmltvid="55114.dvb.guide" where callsign="Planet Pop";
update channel set channum="371" where callsign="Starz TV";
update channel set xmltvid="53335.dvb.guide" where callsign="Starz TV";
update channel set channum="377" where callsign="NOW Music";
update channel set xmltvid="52010.dvb.guide" where callsign="NOW Music";
update channel set channum="378" where callsign="Heart TV";
update channel set xmltvid="55111.dvb.guide" where callsign="Heart TV";
update channel set channum="379" where callsign="CAPITAL TV";
update channel set xmltvid="55112.dvb.guide" where callsign="CAPITAL TV";
update channel set channum="383" where callsign="Clubland TV";
update channel set xmltvid="55113.dvb.guide" where callsign="Clubland TV";
