update channel set channum="401" where callsign="Sky Sp NewsHQ";
update channel set xmltvid="4909.dvb.guide" where callsign="Sky Sp NewsHQ";
update channel set channum="402" where callsign="Sky Sports 1";
update channel set xmltvid="4214.dvb.guide" where callsign="Sky Sports 1";
update channel set channum="403" where callsign="Sky Sports 2";
update channel set xmltvid="5505.dvb.guide" where callsign="Sky Sports 2";
update channel set channum="404" where callsign="Sky Sports 3";
update channel set xmltvid="4219.dvb.guide" where callsign="Sky Sports 3";
update channel set channum="405" where callsign="Sky Sports 4";
update channel set xmltvid="5401.dvb.guide" where callsign="Sky Sports 4";
update channel set channum="406" where callsign="Sky Sports 5";
update channel set xmltvid="1304.dvb.guide" where callsign="Sky Sports 5";
update channel set channum="407" where callsign="Sky Sports F1";
update channel set xmltvid="1306.dvb.guide" where callsign="Sky Sports F1";
update channel set channum="410" where callsign="Eurosport";
update channel set xmltvid="5713.dvb.guide" where callsign="Eurosport";
update channel set channum="411" where callsign="Eurosport 2";
update channel set xmltvid="5009.dvb.guide" where callsign="Eurosport 2";
update channel set channum="414" where callsign="BT Sport 1";
update channel set xmltvid="50366.dvb.guide" where callsign="BT Sport 1";
update channel set channum="413" where callsign="BT Sport 1 HD";
update channel set xmltvid="50661.dvb.guide" where callsign="BT Sport 1 HD";
update channel set channum="416" where callsign="BT Sport 2";
update channel set xmltvid="50376.dvb.guide" where callsign="BT Sport 2";
update channel set channum="415" where callsign="BT Sport 2 HD";
update channel set xmltvid="50666.dvb.guide" where callsign="BT Sport 2 HD";
update channel set channum="417" where callsign="Setanta Ireland";
update channel set xmltvid="51122.dvb.guide" where callsign="Setanta Ireland";
update channel set channum="418" where callsign="Setanta Sports1";
update channel set xmltvid="51123.dvb.guide" where callsign="Setanta Sports1";
update channel set channum="419" where callsign="MUTV";
update channel set xmltvid="50345.dvb.guide" where callsign="MUTV";
update channel set channum="420" where callsign="Chelsea TV";
update channel set xmltvid="5717.dvb.guide" where callsign="Chelsea TV";
update channel set channum="428" where callsign="Premier Sports";
update channel set xmltvid="51113.dvb.guide" where callsign="Premier Sports";
update channel set channum="429" where callsign="LFCTV";
update channel set xmltvid="52225.dvb.guide" where callsign="LFCTV";
update channel set channum="433" where callsign="ESPN HD";
update channel set xmltvid="53795.dvb.guide" where callsign="ESPN HD";
update channel set channum="434" where callsign="ESPN";
update channel set xmltvid="50380.dvb.guide" where callsign="ESPN";
