#!/bin/bash
#Set Date (Duh)
today=$(date '+%d_%m_%y')

####STOP Myth Backend, Until I can work out how to force it to a channel#########

#service mythbackend stop
#stop mythbackend

########  Tune to EPG Data ###########



szap -c /etc/channels.conf EPG &

########### Grab EPG Data ###########

tv_grab_dvb_plus  --format skyuk --output "$today".sky.xml

###### Trim some crap ##########


sed -i 's/ <!-- number.*-->//g' "$today".sky.xml

########### Kill Tuning #########

killall szap


############restart Baqckend#####################


#service mythbackend start
#start mythbackend


################# Fill Database #####################

mythfilldatabase --file --sourceid 1  --xmlfile "$today".sky.xml


#############Remove File#############
rm -rf "$today".sky.xml


######### Write to Log if wanted############


#echo "EPG Imported: $(date)" >> /home/mythtv/epg.log
