#!/bin/bash
#Set Date (Duh)
today=$(date '+%d_%m_%y')

####STOP Myth Backend, Until I can work out how to force it to a channel#########

#service mythbackend stop
#stop mythbackend

#### Tune and Grab EPG

szap -c /etc/channels.conf EPG &
tv_grab_dvb_plus  --format skyuk --output "$today".sky.xml
killall szap

##### Make a copy.

cp "$today".sky.xml "$today".db.xml
sed -i '/<?xml version="/,/<channel id=/d'
sed -i '1,2d' "$today".db.xml
sed -i 's/<!--/ /g'
 sed -i 's/type.*-->>/ /g'
dumpdb sed -i '/<?xml version="/,/<channel id=/d' > Channels.sql
