#!/bin/bash
#Clear existing channel EPG and Junk.
mysql -umythtv -pmythtv -e 'delete from program;' mythconverg
#Move all channels to junk Numbers
mysql -umythtv -pmythtv -e 'update channel set channum="99999;"' mythconverg
#Import Channel numbering data and EPG XML
mysql -u mythtv -pmythtv mythconverg < Music.sql
mysql -u mythtv -pmythtv mythconverg < Entertainment.sql
mysql -u mythtv -pmythtv mythconverg < Sports.sql
mysql -u mythtv -pmythtv mythconverg < Movies.sql
mysql -u mythtv -pmythtv mythconverg < Knowledge.sql
mysql -u mythtv -pmythtv mythconverg < Kids.sql


