#!/bin/bash
today=$(date '+%d_%m_%y')
#service mythbackend stop
#stop mythbackend
szap -c /etc/channels.conf EPG &
tv_grab_dvb_plus  --format skyuk --output "$today".sky.xml
sed -i 's/ <!-- number.*-->//g' "$today".sky.xml
killall szap
#service mythbackend start
#start mythbackend
#mythfilldatabase --file --sourceid 1  --xmlfile "$today".sky.xml
rm -rf "$today".sky.xml
#echo "EPG Imported: $(date)" >> /home/mythtv/epg.log
