#!/bin/bash
sed -i '1 i\LOCK TABLES channel WRITE;' Chanlist.sql
sed -i '$iupdate channel set channum="401",xmltvid="4909.dvb.guide" where callsign="Sky Sp NewsHQ";' Chanlist.sql
sed -i '$iupdate channel set channum="402",xmltvid="4214.dvb.guide" where callsign="Sky Sports 1";' Chanlist.sql
sed -i '$iupdate channel set channum="403",xmltvid="5505.dvb.guide" where callsign="Sky Sports 2";' Chanlist.sql
sed -i '$iupdate channel set channum="404",xmltvid="4219.dvb.guide" where callsign="Sky Sports 3";' Chanlist.sql
sed -i '$iupdate channel set channum="405",xmltvid="5401.dvb.guide" where callsign="Sky Sports 4";' Chanlist.sql
sed -i '$iupdate channel set channum="406",xmltvid="1304.dvb.guide" where callsign="Sky Sports 5";' Chanlist.sql
sed -i '$iupdate channel set channum="407",xmltvid="1306.dvb.guide" where callsign="Sky Sports F1";' Chanlist.sql
sed -i '$iupdate channel set channum="413",xmltvid="50661.dvb.guide" where callsign="BT Sport 1 HD";' Chanlist.sql
sed -i '$iupdate channel set channum="414",xmltvid="50666.dvb.guide" where callsign="BT Sport 2 HD";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="6941.dvb.guide", channum="101" where callsign="BBC One HD";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="6940.dvb.guide", channum="102" where callsign="BBC Two HD";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="21010.dvb.guide", channum="103" where callsign="ITV HD";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="21200.dvb.guide", channum="104" where callsign="Channel 4 HD";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="7701.dvb.guide",  channum="105" where callsign="Channel 5";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="5718.dvb.guide",  channum="106" where callsign="Sky1";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="5715.dvb.guide",  channum="107" where callsign="Sky Living";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="5711.dvb.guide",  channum="108" where callsign="Sky Atlantic ";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="7657.dvb.guide",  channum="109" where callsign="Watch";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="6504.dvb.guide",  channum="110" where callsign="GOLD";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="7620.dvb.guide",  channum="111" where callsign="Dave";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="51084.dvb.guide", channum="112" where callsign="ComedyCentral";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="6951.dvb.guide",  channum="115" where callsign="BBC Three HD";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="8931.dvb.guide",  channum="116" where callsign="BBC Four HD";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="10070.dvb.guide", channum="118" where callsign="ITV2";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="10260.dvb.guide", channum="119" where callsign="ITV3";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="10072.dvb.guide", channum="120" where callsign="ITV4";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="5709.dvb.guide",  channum="121" where callsign="Sky2";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="5712.dvb.guide",  channum="122" where callsign="Sky Living+1";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="5515.dvb.guide",  channum="124" where callsign="FOX";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="4900.dvb.guide",  channum="130" where callsign="Sky Arts 2";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="5719.dvb.guide",  channum="129" where callsign="Sky Arts 1";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="9208.dvb.guide",  channum="136" where callsign="E4";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="8300.dvb.guide",  channum="137" where callsign="E4+1";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="8340.dvb.guide",  channum="138" where callsign="More4";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="6031.dvb.guide",  channum="145" where callsign="Challenge";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="53215.dvb.guide", channum="151" where callsign="E!";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="5716.dvb.guide",  channum="156" where callsign="Lifetime";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="170",xmltvid="1302.dvb.guide" WHERE callsign="Sky 3D";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="7715.dvb.guide",  channum="176" where callsign="5*";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="7720.dvb.guide",  channum="177" where callsign="Channel 5+1";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="54110.dvb.guide", channum="185" where callsign="more>movies";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="51120.dvb.guide", channum="186" where callsign="m>movies+1";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="6208.dvb.guide",  channum="240" where callsign="Home & Health";' Chanlist.sql
sed -i '$iupdate channel set xmltvid="52450.dvb.guide", channum="241" where callsign="Home&Health+";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="315",xmltvid="9220.dvb.guide" WHERE callsign="Film4";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="317",xmltvid="5714.dvb.guide" WHERE callsign="TCM";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="350",xmltvid="7012.dvb.guide" WHERE callsign="MTV MUSIC";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="361",xmltvid="50856.dvb.guide" WHERE callsign="Kiss";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="363",xmltvid="53720.dvb.guide" WHERE callsign="Magic";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="402",xmltvid="5713.dvb.guide" WHERE callsign="Eurosport";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="411",xmltvid="5009.dvb.guide" WHERE callsign="Eurosport 2";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="415",xmltvid="4804.dvb.guide" WHERE callsign="At The Races";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="417",xmltvid="50380.dvb.guide" WHERE callsign="ESPN";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="423",xmltvid="51111.dvb.guide" WHERE callsign="Setanta Ireland";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="424",xmltvid="51112.dvb.guide" WHERE callsign="Setanta Sports1";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="426",xmltvid="50365.dvb.guide" WHERE callsign="BT Sport 1";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="427",xmltvid="50375.dvb.guide" WHERE callsign="BT Sport 2";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="501",xmltvid="4704.dvb.guide" WHERE callsign="Sky News";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="503",xmltvid="10358.dvb.guide" WHERE callsign="BBC NEWS";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="522",xmltvid="52400.dvb.guide" WHERE callsign="ID";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="526",xmltvid="4805.dvb.guide" WHERE callsign="Nat Geo";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="529",xmltvid="4653.dvb.guide" WHERE callsign="History";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="553",xmltvid="4802.dvb.guide" WHERE callsign="CI";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="604",xmltvid="51091.dvb.guide" WHERE callsign="Nickelodeon";' Chanlist.sql
sed -i '$iupdate channel set channum="613", xmltvid="6952.dvb.guide" where callsign="CBBC HD";' Chanlist.sql
sed -i '$iupdate channel set channum="614", xmltvid="8932.dvb.guide" where callsign="CBeebies HD";' Chanlist.sql
sed -i '$iUPDATE channel SET channum="620",xmltvid="51089.dvb.guide" WHERE callsign="Nick Jr Too";' Chanlist.sql
sed -i "\$aUNLOCK TABLES;" Chanlist.sql
